backend:
    name: git-gateway
    branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
    - name: "projects"
      label: "Projects"
      folder: "src/content/projects"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Project URL", name: "url", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
